#  SOLVING SYSTEM OF EQUATIONS

Below are the necessary functions to perform Gauss Elimination depending on your data source. please execute the functions in the cells below



*   **collect_data ()**        : to input data from keyboard and returns two matrices
*   **collect_df_data ()**     : to collect data from excel or csv
*   **collect_text_file ()**   : to collect data from a file


*



1.   **gauss_elimination (eqn, const)** : to carry out gauss elimination on n - matrices

2.   **gauss_jordan_elimination (eqn, const)** : to carry out gauss-jordan elimination on n x n - matrices

3.   **LU_decomp_crout_operation (eqn_test, const):** to carry out LU decomposition on n x n - matrices
4.    **matrix_inv ():**  to carry out matrix inverse on n x n - matrices




*   testing data can be found below. uncomment and pass it as an argument





In [ ]:
# importing necessary libaries

import pandas as pd
import numpy as np


# ANSI codes for colors
class Color:
    RESET = "\033[0m"
    RED = "\033[91m"
    GREEN = "\033[92m"
    YELLOW = "\033[93m"
    BLUE = "\033[94m"
    PURPLE = "\033[95m"
    CYAN = "\033[96m"
    WHITE = "\033[97m"

In [ ]:
# program to calculate the solution of n linear system of equations using gauss elimination method

# function to receive equation input from users
# the constant is in the format "x_1, x_2, .....x_n"

def collect_data ():
  while True:
    try:
      row = int(input("Enter the number of Equations: \n (ensure that the number of equations is equal to number of variables)"))
      break
    except:
      print(Color.RED + "ERROR:Enter a valid number: " + Color.RESET)
  eqn = []
  for a in range(row):
    while True:
      try:
        while True:
          row_eqn = [float(x) for x in input(f"Enter Equation values for row {a+1} separated by space: ").split()]
          if len (row_eqn) == row:
            break
          else:
            print(Color.RED + f"Missing values present /n Enter {row} values for each row: " + Color.RESET)
        eqn.append(row_eqn)
        break
      except:
        print(Color.RED + "ERROR: Enter valid numbers separated by space: " + Color.RESET)
  while True:
    try:
      const = [float(y) for y in input(f"\n Enter Constant values separated by space: ").split()]
      break
    except:
      print(Color.RED + "ERROR: Enter valid numbers separated by space: " + Color.RESET)

  eqn = np.array(eqn)
  const = np.array(const)
  return eqn, const


# function to collect data from excel and csv files
def collect_df_data (file_path, sheet_name=None, header = None):
    """
    Read matrices from Excel and CSV files.

    Parameters:
    - file_path: The path to the file (Excel or CSV) containing matrices.
    - sheet_name: (Only for Excel) The name of the sheet to read. If None, reads the first sheet.

    Returns:
    - A list of matrices represented as NumPy arrays.
    """
    if file_path.endswith(".xlsx") or file_path.endswith(".xls"):
        # Read Excel file
        try:
            df = pd.read_excel(file_path, sheet_name=sheet_name, header=header)
        except Exception as e:
            print(f"Error reading Excel file: {e}")
            return None
    elif file_path.endswith(".csv"):
        # Read CSV file
        try:
            df = pd.read_csv(file_path, header=None)
        except Exception as e:
            print(f"Error reading CSV file: {e}")
            return None
    else:
        print("Unsupported file format. Supported formats: Excel (.xlsx, .xls), CSV (.csv)")
        return None

    # Convert DataFrame to NumPy array
    try:
        ar_eqn = [df.to_numpy()]
    except Exception as e:
        print(f"Error converting DataFrame to NumPy array: {e}")
        return None

    return ar_eqn

# function to collect the matrix data from a file
def collect_text_file ():
  file_name = input("Enter file name: \n include file path if different from python file: ")

  # reading the content of the text file and creating a matrix
  with open(filename, "r") as file:
    ar_eqn = [list(map(int, line.split())) for line in file.readlines()]
  # carry out gauss elimination
  return ar_eqn


def gauss_elimination (eqn, const):
  # augmenting the matrices
  ar_eqn = np.column_stack((eqn, const))

  # creating array for solution
  no_row, no_col = np.shape(ar_eqn)
  soln = np.zeros(no_row)
  L = np.zeros((no_row, no_col))

  # checking data and carrying out neccessary pivoting
  for m in range(0, no_row-1):
    if ar_eqn[m, m] == 0:
      for k in range(m+1, no_col):
        if ar_eqn[k, m] != 0:
          m_temp = ar_eqn[m].copy()
          ar_eqn[m] = ar_eqn[k]
          ar_eqn[k] = m_temp
          #print(ar_eqn)
          break


    # carrying out forward elimination
    for n in range (m+1, no_row):
      mul = ar_eqn[n][m] / ar_eqn[m][m]
      L[n, m] = mul
      for k in range(no_col):
        ar_eqn[n][k] = ar_eqn[n][k] - mul * ar_eqn[m][k]

  # carrying out backward substitution
  soln[-1] = ar_eqn[-1][-1]/ar_eqn[-1][-2]
  for i in range(no_row-2, -1, -1):
    var = ar_eqn[i][-1]
    for j in range(i+1, no_row):
      var -= ar_eqn[i][j]*soln[j]
    soln[i] = var /ar_eqn[i][i]

  # printing the values of variables
  for s in range(no_row):
    print("x_%d = %0.4f" %(s+1, soln[s]), end = "\t")

  print(L)
  print("\n \n")
  print(ar_eqn)
  return soln


def gauss_jordan_elimination (eqn, const):
  # augmenting the matrices
  ar_eqn = np.column_stack((eqn, const))

  # creating solution and iteration variable
  no_row, no_col = np.shape(aug_eqn)
  soln = np.zeros(no_row)


  # checking and pivoting elements where necessary
  for i in range(no_row):
    if aug_eqn[i][i] == 0:
      for k in range(i+1, no_col):
        if aug_eqn[k][i] != 0:
          temp = aug_eqn[i].copy()
          aug_eqn[i] = aug_eqn[k]
          aug_eqn[k] = temp
          break

    # carrying out gauss_jordan elimination
    aug_eqn[i] = aug_eqn[i]/aug_eqn[i][i]
    for j in range (no_row):
      if i != j:
        mul = aug_eqn[j][i]/aug_eqn[i][i]
        aug_eqn[j] = aug_eqn[j] - aug_eqn[i] * mul


    # getting the solution
  soln = aug_eqn[:, -1]

    # printing and returning solution
  for s in range(no_row):
    print("x_%d = %0.4f" %(s+1, soln[s]), end = "\t")
  return soln

In [ ]:
# program to carryout LU decomposition with pivoting on matrices

def LU_decomp_crout (a_eqn):
  no_row, no_col = np.shape(a_eqn)
  L = np.zeros((no_row, no_col))
  U = np.zeros((no_row, no_col))

  # carrying out pivoting
  p = np.zeros((no_row, no_col))
  for i in range (no_row):
    p[i, i] = 1

  for m in range(0, no_row-1):
    if a_eqn[m, m] == 0:
      for k in range(m+1, no_col):
        if a_eqn[k, m] != 0:
          m_temp = a_eqn[m].copy()
          a_eqn[m] = a_eqn[k]
          a_eqn[k] = m_temp
          p_temp = p[m].copy()
          p[m] = p[k]
          p[k] = p_temp
          break

  #getting the first row of the L column
  for i in range(no_row):
    L[i, 0] = a_eqn[i, 0]

  # putting the diagonal of U
  for j in range (no_row):
    U[j, j] = 1

  # calculating the first row of matrix U
  for a in range (1, no_col):
    U[0, a] = a_eqn[0, a] / L[0, 0]

  # calculating the other rows of matrix L and U
  for i in range (1, no_row):
    for j in range (1, i+1):
      L[i, j] = a_eqn[i, j] -np.sum(L[i, :j] * U[:j, j])

    for j in range (i + 1, no_row):
      U[i, j] = (a_eqn[i, j] - np.sum(L[i, :i] * U[:i, j]))/L[i, i]

  return L, U, p

# carrying forward substitution on the matrix
def forwardsub (L, p, const):
  no_row, no_col = np.shape(L)
  const = np.dot (p, const)
  soln = np.zeros(no_row)
  soln[0] = const[0]/L[0][0]

  for i in range (1, no_row):
    var = 0
    for j in range (0, i):
      var = var + L[i][j] * soln[j]
    soln[i] = (const[i] - var) / L[i][i]
  return soln

# carrying out backward substitution on the matrix
def backwardsub (U, L_soln):
  no_row, no_col = np.shape(U)
  soln = np.zeros(no_row)
  soln[-1] = L_soln[-1]

  for i in range (no_row-2, -1, -1):
    var = 0
    for j in range (i+1, no_row):
      var += U[i][j]*soln[j]
    soln[i] = L_soln[i] - var
  return soln

# carrying out the LU Decomposition procedure to find the solution to the matrix
def LU_decomp_crout_operation (eqn_test, const):
  L, U, p= LU_decomp_crout (eqn_test)
  L_soln = forwardsub (L, p, const)
  soln = backwardsub (U, L_soln)

  for a in range(len(soln)):
    print("x_%d = %0.4f" %(a+1, soln[a]))

  return soln


In [ ]:
# program to find the inverse of the matrix

def matrix_inv (eqn):
  eqn = np.array(eqn)
  no_row, no_col = np.shape(eqn)

  # checking that the matrix is square and creating null matrices
  while True:
    try:
      if no_row == no_col:
        I = np.zeros ((no_row, no_col))
        inv = np.zeros((no_row, no_col))
        break
      else:
        print ("Enter a valid matrix with equal rows and columns")
        break
        sys.exit ()
    except:
      print ("check the inputs of the matrix")

  # creating an identity matrix
  for a in range (no_row):
    I[a, a] = 1

  # carryout LU decomposition with pivoting
  L, U, p = LU_decomp_crout (eqn)

  for i in range (no_row):
    I_col = I[:, i]
    L_soln = forwardsub (L, p, I_col)
    inv_row = backwardsub (U, L_soln)
    inv[:, i] = inv_row

  return inv




In [ ]:

eqn = [
    [0, 0.9231, 0, 0, 0, 0, 0, 0],
    [-1, -0.3846, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 1, 0, 0.8575, 0],
    [1, 0, -0.7809, 0, 0, 0, 0, 0],
    [0, -0.3846, -0.7809, 0, -1, 0.3846, 0, 0],
    [0, 0.9231, 0.6247, 0, 0, -0.9231, 0, 0],
    [0, 0, 0.6247, -1, 0, 0, 0, 0],
    [0, 0, 0, 1, 0, 0, -0.5145, -1]
]

const = [1690, 3625, 0, 0, 0, 0, 0, 0]
#test = np.column_stack((eqn, const))

matrix_inv (eqn)

array([[-0.41663958, -1.        , -0.        , -0.        , -0.        ,
        -0.        , -0.        , -0.        ],
       [ 1.08330625,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ],
       [-0.53353769, -1.2805737 , -0.        , -1.2805737 , -0.        ,
        -0.        , -0.        , -0.        ],
       [-0.333301  , -0.79997439, -0.        , -0.79997439, -0.        ,
        -0.        , -1.        , -0.        ],
       [ 0.2777732 ,  0.666699  , -0.        ,  0.666699  , -1.        ,
        -0.41663958, -0.        , -0.        ],
       [ 0.7222392 , -0.86661726, -0.        , -0.86661726, -0.        ,
        -1.08330625, -0.        , -0.        ],
       [-0.32393376, -0.77749155,  1.16618076, -0.77749155,  1.16618076,
         0.48587707,  0.        ,  0.        ],
       [-0.16663708, -0.39995499, -0.6       , -0.39995499, -0.6       ,
        -0.24998375, -1.        , -1.        ]])

In [ ]:
eqn = [
    [4, -2, -3, 6],
    [-6, 7, 6.5, -6],
    [1, 7.5, 6.25, 5.5],
    [-12, 22, 15.5, -1]
]
eqn_test = np.array(eqn)

const = [12, -6.5, 16, 17]
const = np.array(const)


gauss_elimination (eqn_test, const)

x_1 = 2.0000	x_2 = 4.0000	x_3 = -3.0000	x_4 = 0.5000	[[ 0.    0.    0.    0.    0.  ]
 [-1.5   0.    0.    0.    0.  ]
 [ 0.25  2.    0.    0.    0.  ]
 [-3.    4.   -0.5   0.    0.  ]]

 

[[  4.   -2.   -3.    6.   12. ]
 [  0.    4.    2.    3.   11.5]
 [  0.    0.    3.   -2.  -10. ]
 [  0.    0.    0.    4.    2. ]]


array([ 2. ,  4. , -3. ,  0.5])

In [ ]:
eqn = [
    [0, 0.9231, 0, 0, 0, 0, 0, 0],
    [-1, -0.3846, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 1, 0, 0.8575, 0],
    [1, 0, -0.7809, 0, 0, 0, 0, 0],
    [0, -0.3846, -0.7809, 0, -1, 0.3846, 0, 0],
    [0, 0.9231, 0.6247, 0, 0, -0.9231, 0, 0],
    [0, 0, 0.6247, -1, 0, 0, 0, 0],
    [0, 0, 0, 1, 0, 0, -0.5145, -1]
]

const = [1690, 3625, 0, 0, 0, 0, 0, 0]
test = np.array(eqn)
LU_decomp_crout_operation (test)

In [ ]:
eqn, const = collect_data()
LU_decomp_crout_operation (eqn, const)

Enter the number of Equations: 
 (ensure that the number of equations is equal to number of variables)4
Enter Equation values for row 1 separated by space: 9 -4 -2 0
Enter Equation values for row 2 separated by space: -4 17 -6 -3
Enter Equation values for row 3 separated by space: -2 -6 14
Enter Equation values for row 4 separated by space: 0 -3 -6 11

 Enter Constant values separated by space: 24 -16 


<ipython-input-7-0fdde1389c87>:29: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  eqn = np.array(eqn)


ValueError: ignored

In [ ]:
# equation to test the inverse of a matrix
a = [
    [0.2, -5, 3, 0.4, 0],
    [-0.5, 1, 7, -2, 0.3],
    [0.6, 2, -4, 3, 0.1],
    [3, 0.8, 2, -0.4, 3],
    [0.5, 3, 2, 0.4, 1]
]

eqn = np.array(a)
eqn_inv = matrix_inv(eqn)

check = np.dot(eqn, eqn_inv)
check

array([[ 1.00000000e+00,  3.55271368e-15,  7.10542736e-15,
        -5.32690064e-15, -4.44089210e-16],
       [-5.55111512e-17,  1.00000000e+00,  2.22044605e-16,
        -2.50780169e-16, -5.55111512e-17],
       [-2.77555756e-17,  1.66533454e-16,  1.00000000e+00,
        -2.53462148e-16, -5.55111512e-17],
       [-2.77555756e-17, -1.22124533e-15,  2.22044605e-16,
         1.00000000e+00,  0.00000000e+00],
       [-4.44089210e-16, -2.66453526e-15,  1.77635684e-15,
        -3.92166094e-17,  1.00000000e+00]])

In [ ]:
eqn_inv

array([[-0.70794915,  2.53143336,  2.43119586,  0.96657586, -3.90227717],
       [-0.19343159,  0.3101425 ,  0.27946587,  0.05771514, -0.29413477],
       [ 0.02168902,  0.36546521,  0.28614837,  0.05055532, -0.28992037],
       [ 0.27341203, -0.12992456,  0.13161265, -0.14101355,  0.44885676],
       [ 0.7815265 , -2.87510478, -2.67893732, -0.70113859,  4.23384092]])

In [ ]:
eqn * eqn_inv

array([[ -0.14158983, -12.65716681,   7.29358759,   0.38663034,
         -0.        ],
       [  0.0967158 ,   0.3101425 ,   1.95626106,  -0.11543029,
         -0.08824043],
       [  0.01301341,   0.73093043,  -1.14459346,   0.15166597,
         -0.02899204],
       [  0.8202361 ,  -0.10393965,   0.2632253 ,   0.05640542,
          1.34657027],
       [  0.39076325,  -8.62531433,  -5.35787464,  -0.28045543,
          4.23384092]])

In [ ]:
9 -4 -2 0
-4 17 -6 -3
-2 -6 14 -6
0 -3 -6 11

24 -16 0 18

In [ ]:
type(eqn)

list